{
 "title": "Minio: Component Metrics",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(minio_total_disks,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Go Routines",
   "type": "graph",
   "description": "Instantaneous number of active goroutines in the process.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(go_goroutines{instance=~\"$host\"}) by(instance)",
     "legendFormat": "minio"
    }
   ]
  },
  {
   "title": "Garbage Collector Pause Duration",
   "type": "graph",
   "description": "Duration in nanoseconds of the last garbage collector pause.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(go_gc_duration_seconds{instance=~\"$host\"}) by(instance)",
     "legendFormat": "minio"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "description": "Instantaneous count of bytes allocated on the heap and still in use.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(go_memstats_heap_alloc_bytes{instance=~\"$host\"}) by(instance)",
     "legendFormat": "minio"
    }
   ]
  },
  {
   "title": "Stack Allocator Memory Usage",
   "type": "graph",
   "description": "Instantaneous count of bytes used by the stack allocator.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(go_memstats_stack_sys_bytes{instance=~\"$host\"}) by(instance)",
     "legendFormat": "minio"
    }
   ]
  }
 ]
}